### ISSUE TITLE
Admit that Java is more versatile.

### ISSUE THREAD

**Issue by rclayton** [jar349/sht1x4j#1]
Add to README.md that a C# programmer is forced to admit that Java is a superior platform.

**Comment by jar349** [comment]
Given that the same sensor may be controlled on a netduino (see here: https://mfweatherstation.codeplex.com/), I do not feel that this is an issue.  It's too bad you don't have a PHP repository so that I can create an issue: "this project is written in PHP".

Ha! :-)

**Comment by rclayton** [comment]
I will not willingly create a PHP open source project.  I may fork a project to fix a mistake, but I will not be party to the continuation of a language that should not exist.
